version: '3.9'

services:
  postgresDb:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contasapp
    ports:
      - '5432:5432'
    volumes:
      - pgData:/var/lib/postgresql
    networks:
      - contasapp_net

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDb:5432/contasapp
    depends_on:
      - postgresDb
    links:
      - postgresDb
    networks:
      - contasapp_net

networks:
   contasapp_net:
       driver: bridge

volumes:
   pgData: