version: '3.9'

services:
  postgres:
     image: postgres:16.1
     restart: always
     environment:
       POSTGRES_PASSWORD: ${DB_LOCAL_PASSWORD}
       POSTGRES_USER: ${DB_LOCAL_USER}
       POSTGRES_DB: ${DB_LOCAL_NAME}
     volumes:
       - pgData:/var/lib/postgres/data
     ports:
       - '5432:5432'
     env_file:
       - .env
     networks:
     - contas_app_net

  app:
     container_name: contasapp
     restart: always
     ports:
       - '8080:8080'
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       SPRING-DATASOURCE-USERNAME: ${DB_LOCAL_USER}
       SPRING-DATASOURCE-PASSWORD: ${DB_LOCAL_PASSWORD}
       SPRING-DATASOURCE-URL: ${DB_LOCAL_URL}
     depends_on:
       - postgres
     networks:
       - contas_app_net
volumes:
   pgData:

networks:
  contas_app_net:
    driver: bridge
