version: '3.9'

services:
  postgresDb:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_LOCAL_USER}
      POSTGRES_PASSWORD: ${DB_LOCAL_PASSWORD}
      POSTGRES_DB: ${DB_LOCAL_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgData:/var/lib/postgresql
    networks:
      - contasapp_net

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_USERNAME: ${DB_LOCAL_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_LOCAL_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDb:5432/${DB_LOCAL_DATABASE_NAME}
    depends_on:
      - postgresDb
    links:
      - postgresDb
    networks:
      - contasapp_net

networks:
   contasapp_net:
       driver: bridge

volumes:
   pgData: