spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://postgresDb:5432/contasapp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false