name: developer
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTest=true

  validate_quality:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Validate Code With Super-Lint
       uses: super-linter/super-linter@v5.7.2
          

