name: homolog

on:
  push:
    branches: [ "homolog" ]
  pull_request:
    branches: [ "dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
  deployImage:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
       username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
       password: ${{ secrets.DOCKER_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
       ecr: auto
        # Log out from the Docker registry at the end of a job
       logout: false
    - name: Docker Metadata action
      uses: docker/metadata-action@v5.5.0
      with:
        context: workflow
        github-token: ${{secrets.GIT_HUB_TOKEN}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        tags: luke0195/contasapp:${{git.run_number}}
        github-token: ${{ secrets.GIT_HUB_TOKEN }}
              
            
        
                  
