name: homolog

on:
  push:
    branches: [ "homolog" ]
  pull_request:
    branches: [ "dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
  deployImage:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
       username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
       password: ${{ secrets.DOCKER_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
       ecr: auto
        # Log out from the Docker registry at the end of a job
       logout: false
    - name: Docker Metadata action
      uses: docker/metadata-action@v5.5.0
      with:
        context: workflow
        # List of Docker images to use as base name for tags
      # images: # optional
        # List of tags as key-value pair attributes
       # tags: # optional
        # Flavors to apply
      #  flavor: # optional
        # List of custom labels
       # labels: # optional
        # List of custom annotations
      #  annotations: # optional
        # Separator to use for tags output (default \n)
     #   sep-tags: # optional
        # Separator to use for labels output (default \n)
      #  sep-labels: # optional
        # Separator to use for annotations output (default \n)
      #  sep-annotations: # optional
        # Bake target name (default docker-metadata-action)
      #  bake-target: # optional
        # GitHub Token as provided by secrets
        github-token: ${{secrets.GIT_HUB_TOKEN}}
    
                  
