name: homolog

on:
  push:
    branches: [ "homolog" ]
  pull_request:
    branches: [ "dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
  deployImage:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
       username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
       password: ${{ secrets.DOCKER_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
       ecr: auto
        # Log out from the Docker registry at the end of a job
       logout: false
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: thetips4you/testjodejsapp
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
              
